SELECT
 VaultAccount.DiscoveredTime AS AccountDiscoveredTime,
 VaultAccount.ActiveCheckouts,
 VaultAccount.ActiveSessions,
 VaultDomain.AllowPasswordHistoryCleanUp,
 VaultAccount.CloudProviderId,
 VaultAccount.ComputerClass,
 VaultAccount.CredentialId,
 VaultAccount.CredentialType,
 VaultAccount.DatabaseID,
 VaultAccount.DefaultCheckoutTime,
 VaultAccount.Description,
 VaultAccount.DeviceID,
 VaultDomain.ID AS DomainID,
 VaultDomain.DiscoveredTime AS DomainDiscoveredTime,
 VaultDomain.Description AS DomainDescription,
 VaultAccount.DueBack,
 VaultAccount.EffectiveWorkflowApprover,
 VaultAccount.EffectiveWorkflowApprovers,
 VaultAccount.EffectiveWorkflowEnabled,
 VaultAccount.FQDN,
 VaultAccount.HealthError,
 VaultAccount.Healthy,
 VaultAccount.Host,
 VaultAccount.ID,
 VaultAccount.IsFavorite,
 VaultAccount.IsManaged,
 VaultAccount.IsPrivileged,
 VaultAccount.IsQuickStartAccount,
 VaultAccount.IsRootAccount,
 VaultAccount.IsServiceAccount,
 VaultAccount.KmipId,
 VaultAccount.LastChange,
 VaultAccount.LastHealthCheck,
 VaultAccount.MissingPassword,
 VaultAccount.Mode,
 VaultAccount.MPParent,
 VaultDomain.Name,
 VaultAccount.NeedsPasswordReset,
 VaultAccount.OwnerId,
 VaultAccount.OwnerName,
 VaultDomain.PasswordHistoryCleanUpDuration,
 VaultAccount.PasswordResetLastError,
 VaultAccount.PasswordResetRetryCount,
 VaultAccount.ProxyUser,
 VaultDomain.ProxyCollectionList,
 VaultAccount.RoleArn,
 VaultAccount.SessionType,
 VaultAccount.Status,
 VaultAccount.User,
 VaultAccount.UserDisplayName,
 VaultAccount.UseWheel,
 VaultAccount.ID AS VaultAccountID,
 VaultAccount.VaultId,
 VaultAccount.VaultSite,
 VaultAccount.WorkflowApprover,
 VaultAccount.WorkflowApprovers,
 VaultAccount.WorkflowApproversList,
 VaultAccount.WorkflowDefaultOptions,
 VaultAccount.WorkflowEnabled
 
FROM
 VaultDomain
 
JOIN
 VaultAccount
 
ON
 VaultAccount.DomainID = VaultDomain.ID
