SELECT
 VaultAccount.DiscoveredTime AS AccountDiscoveredTime,
 VaultAccount.ActiveCheckouts,
 VaultAccount.ActiveSessions,
 VaultDatabase.AllowPasswordHistoryCleanUp,
 VaultAccount.ClientId,
 VaultAccount.CloudProviderId,
 VaultAccount.ComputerClass,
 VaultAccount.CredentialId,
 VaultAccount.CredentialType,
 VaultDatabase.ID AS DatabaseID,
 VaultDatabase.Description AS DatabaseDescription,
 VaultDatabase.DatabaseClass,
 VaultAccount.DefaultCheckoutTime,
 VaultAccount.Description,
 VaultAccount.DeviceID,
 VaultAccount.DomainID,
 VaultAccount.DueBack,
 VaultAccount.EffectiveWorkflowApprover,
 VaultAccount.EffectiveWorkflowApprovers,
 VaultAccount.EffectiveWorkflowEnabled,
 VaultAccount.FQDN,
 VaultAccount.HealthError,
 VaultAccount.Healthy,
 VaultAccount.Host,
 VaultAccount.ID,
 VaultAccount.IsFavorite,
 VaultAccount.IsManaged,
 VaultAccount.IsPrivileged,
 VaultAccount.IsQuickStartAccount,
 VaultAccount.IsRootAccount,
 VaultAccount.IsServiceAccount,
 VaultAccount.KmipId,
 VaultAccount.LastChange,
 VaultAccount.LastHealthCheck,
 VaultAccount.MissingPassword,
 VaultAccount.Mode,
 VaultAccount.MPParent,
 VaultDatabase.Name AS Name,
 VaultAccount.NeedsPasswordReset,
 VaultAccount.OwnerId,
 VaultAccount.OwnerName,
 VaultAccount.PasswordResetLastError,
 VaultAccount.PasswordResetRetryCount,
 VaultDatabase.PasswordHistoryCleanUpDuration,
 VaultDatabase.ProxyCollectionList,
 VaultAccount.ProxyUser,
 VaultAccount.RoleArn,
 VaultAccount.SessionType,
 VaultAccount.Status,
 VaultAccount.User,
 VaultAccount.UserDisplayName,
 VaultAccount.UseWheel,
 VaultAccount.ID AS VaultAccountID,
 VaultAccount.VaultId,
 VaultAccount.VaultSite,
 VaultAccount.WorkflowApprover,
 VaultAccount.WorkflowApprovers,
 VaultAccount.WorkflowApproversList,
 VaultAccount.WorkflowDefaultOptions,
 VaultAccount.WorkflowEnabled
 
FROM
 VaultAccount
 
JOIN
 VaultDatabase
 
ON
 VaultAccount.DatabaseID = VaultDatabase.ID