SELECT
 VaultAccount.DiscoveredTime AS AccountDiscoveredTime,
 VaultAccount.ActiveCheckouts,
 VaultAccount.ActiveSessions,
 Server.AllowPasswordHistoryCleanUp,
 VaultAccount.CloudProviderId,
 Server.ComputerClass,
 VaultAccount.CredentialId,
 VaultAccount.CredentialType,
 VaultAccount.DatabaseID,
 VaultAccount.DefaultCheckoutTime,
 VaultAccount.Description,
 Server.Description AS ServerDescription,
 VaultAccount.DeviceID,
 VaultAccount.DomainID,
 VaultAccount.DueBack,
 VaultAccount.EffectiveWorkflowApprover,
 VaultAccount.EffectiveWorkflowApprovers,
 VaultAccount.EffectiveWorkflowEnabled,
 Server.FQDN,
 VaultAccount.HealthError,
 VaultAccount.Healthy,
 VaultAccount.Host,
 VaultAccount.ID,
 VaultAccount.IsFavorite,
 VaultAccount.IsManaged,
 VaultAccount.IsPrivileged,
 VaultAccount.IsQuickStartAccount,
 VaultAccount.IsRootAccount,
 VaultAccount.IsServiceAccount,
 VaultAccount.KmipId,
 VaultAccount.LastChange,
 VaultAccount.LastHealthCheck,
 VaultAccount.MissingPassword,
 VaultAccount.Mode,
 VaultAccount.MPParent,
 Server.Name,
 VaultAccount.NeedsPasswordReset,
 VaultAccount.OwnerId,
 VaultAccount.OwnerName,
 Server.PasswordHistoryCleanUpDuration,
 VaultAccount.PasswordResetLastError,
 VaultAccount.PasswordResetRetryCount,
 Server.Port,
 Server.ProxyUser,
 Server.ProxyCollectionList,
 VaultAccount.RoleArn,
 Server.ID AS ServerID,
 Server.DiscoveredTime AS ServerDiscoveredTime,
 Server.SessionType,
 VaultAccount.Status,
 VaultAccount.User,
 VaultAccount.UserDisplayName,
 VaultAccount.UseWheel,
 VaultAccount.ID AS VaultAccountID,
 VaultAccount.VaultId,
 VaultAccount.VaultSite,
 VaultAccount.WorkflowApprover,
 VaultAccount.WorkflowApprovers,
 VaultAccount.WorkflowApproversList,
 VaultAccount.WorkflowDefaultOptions,
 VaultAccount.WorkflowEnabled
 
FROM
 VaultAccount
 
JOIN
 Server
 
ON
 VaultAccount.Host = Server.ID
